const DB="corte_paquetes_v1_6",$=id=>document.getElementById(id);
function wk(d){d=new Date(d);d.setHours(0,0,0,0);d.setDate(d.getDate()+3-(d.getDay()+6)%7);let y=d.getFullYear(),f=new Date(y,0,4);return y+"-"+(1+Math.round(((d-f)/864e5-f.getDay()+1)/7))}
const dk=d=>{d=new Date(d);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")},pd=s=>{let[a,b,c]=s.split("-").map(Number);return new Date(a,b-1,c)};
function bounds(){let n=new Date(),m=new Date(n),day=(n.getDay()+6)%7;m.setDate(n.getDate()-day);m.setHours(0,0,0,0);let s=new Date(m);s.setDate(m.getDate()+6);s.setHours(23,59,59,999);return[m,s]}
const load=()=>{try{return Object.assign({data:{},rates:{},advances:{},settings:{shade:62,blur:8,bg:null}},JSON.parse(localStorage.getItem(DB)||"{}"))}catch{return{data:{},rates:{},advances:{},settings:{shade:62,blur:8,bg:null}}}},save=x=>localStorage.setItem(DB,JSON.stringify(x)),money=n=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(n);
function rate(db,date){let k=Object.keys(db.rates||{}).filter(x=>x<=date).sort();return k.length?+db.rates[k[k.length-1]]:0}
function refresh(){let db=load(),w=wk(new Date()),es=Object.entries(db.data).filter(([k])=>k.startsWith(w+"_")).map(([k,v])=>({date:k.slice(3),v:+v})),r=rate(db,dk(new Date())),total=es.reduce((s,e)=>s+e.v,0),ad=db.advances?.[w]||[],at=ad.reduce((s,x)=>s+ +x.amount,0),[mon,sun]=bounds();$("week").textContent="Semana "+w.split("-")[1];$("range").textContent=`Lunes ${mon.getDate()} – Domingo ${sun.getDate()} de ${sun.toLocaleDateString("es-MX",{month:"long",year:"numeric"})}`;$("total").textContent=total;$("gross").textContent=money(total*r);$("rateText").textContent=money(r);$("adv").textContent="-"+money(at);$("advCount").textContent=ad.length;$("net").textContent=money(total*r-at);$("daysText").textContent=es.length?es.length+" días registrados":"Sin registros";$("count").textContent=es.length+" días";$("curRate").textContent=money(r);$("rate").value=r||"";$("date").min=dk(mon);$("date").max=dk(sun);if(!$("date").value||$("date").value<$("date").min||$("date").value>$("date").max)$("date").value=dk(new Date());$("advDate").min=dk(mon);$("advDate").max=dk(sun);if(!$("advDate").value||$("advDate").value<$("advDate").min||$("advDate").value>$("advDate").max)$("advDate").value=dk(new Date());$("list").innerHTML=es.length?es.sort((a,b)=>a.date.localeCompare(b.date)).map(e=>{let d=pd(e.date),rr=rate(db,e.date);return `<div class=row><div class=date>${d.toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"})}<small>${d.toLocaleDateString("es-MX",{weekday:"long"})}</small></div><div class=rowRight><b>${e.v} paquetes</b><small>${money(e.v*rr)}</small></div><div><button class=mini onclick="editDay('${e.date}')">✏️</button><button class=mini onclick="delDay('${e.date}')">🗑️</button></div></div>`}).join(""):"Aún no hay registros.";$("advList").innerHTML=ad.length?ad.map((x,i)=>`<div class=row><div class=date>${esc(x.concept)}<small>${pd(x.date).toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"})}</small></div><div class=rowRight><b>-${money(x.amount)}</b></div><button class=mini onclick="delAdv(${i})">🗑️</button></div>`).join(""):"No hay adelantos.";let ws=[...new Set(Object.keys(db.data).map(k=>k.split("_")[0]))].sort().reverse();$("history").innerHTML=ws.length?ws.map(x=>{let en=Object.entries(db.data).filter(([k])=>k.startsWith(x+"_")),t=en.reduce((s,[,v])=>s+ +v,0),last=en.map(([k])=>k.slice(3)).sort().pop(),rr=last?rate(db,last):0,a=(db.advances?.[x]||[]).reduce((s,z)=>s+ +z.amount,0);return `<div class=row><div class=date>Semana ${x.split("-")[1]}<small>${money(rr)} / paquete · adelantos ${money(a)}</small></div><div class=rowRight><b>${t} paquetes</b><small>${money(t*rr-a)} a recibir</small></div></div>`}).join(""):"Todavía no hay semanas anteriores.";apply(db.settings)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
$("save").onclick=()=>{let n=+$("qty").value,date=$("date").value,[m,s]=bounds(),d=pd(date);if(!Number.isFinite(n)||n<0||d<m||d>s){alert("Selecciona un día de la semana actual, de lunes a domingo.");return}let db=load();db.data[wk(d)+"_"+date]=Math.floor(n);save(db);$("qty").value="";refresh()};
$("saveRate").onclick=()=>{let n=+$("rate").value;if(!Number.isFinite(n)||n<0)return;let db=load();db.rates[dk(new Date())]=n;save(db);refresh()};
$("addAdv").onclick=()=>{$("advDate").value=dk(new Date());$("advPanel").classList.remove("hidden")};$("cancelAdv").onclick=()=>$("advPanel").classList.add("hidden");
$("saveAdv").onclick=()=>{let a=+$("amount").value,c=$("concept").value.trim()||"Préstamo",date=$("advDate").value,[m,s]=bounds(),d=pd(date);if(!Number.isFinite(a)||a<=0||d<m||d>s){alert("Selecciona un día de la semana actual.");return}let db=load(),w=wk(d);db.advances[w]??=[];db.advances[w].push({amount:a,concept:c,date});save(db);$("advPanel").classList.add("hidden");$("amount").value="";$("concept").value="";refresh()};
window.delAdv=i=>{if(!confirm("¿Eliminar adelanto?"))return;let db=load(),w=wk(new Date);db.advances[w].splice(i,1);save(db);refresh()};
window.editDay=s=>{$("editPanel").dataset.date=s;$("editTitle").textContent="Editar "+pd(s).toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"});$("editQty").value=load().data[wk(pd(s))+"_"+s]||0;$("editPanel").classList.remove("hidden")};
$("cancelEdit").onclick=()=>$("editPanel").classList.add("hidden");$("saveEdit").onclick=()=>{let s=$("editPanel").dataset.date,n=+$("editQty").value;if(!Number.isFinite(n)||n<0)return;let db=load();db.data[wk(pd(s))+"_"+s]=Math.floor(n);save(db);$("editPanel").classList.add("hidden");refresh()};
window.delDay=s=>{if(!confirm("¿Eliminar registro?"))return;let db=load();delete db.data[wk(pd(s))+"_"+s];save(db);refresh()};
$("reset").onclick=()=>{if(!confirm("¿Borrar registros y adelantos de esta semana?"))return;let db=load(),w=wk(new Date);Object.keys(db.data).filter(k=>k.startsWith(w+"_")).forEach(k=>delete db.data[k]);delete db.advances[w];save(db);refresh()};
$("settings").onclick=()=>$("setPanel").classList.remove("hidden");$("closeSet").onclick=()=>$("setPanel").classList.add("hidden");
$("bg").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let db=load();db.settings.bg=r.result;save(db);apply(db.settings)};r.readAsDataURL(f)};$("removeBg").onclick=()=>{let db=load();db.settings.bg=null;save(db);apply(db.settings)};$("shadeRange").oninput=e=>{let db=load();db.settings.shade=+e.target.value;save(db);apply(db.settings)};$("blurRange").oninput=e=>{let db=load();db.settings.blur=+e.target.value;save(db);apply(db.settings)};
function apply(s={}){$("shadeRange").value=s.shade??62;$("blurRange").value=s.blur??8;$("shadeOut").textContent=(s.shade??62)+"%";$("blurOut").textContent=(s.blur??8)+"px";$("shade").style.background=`rgba(3,7,18,${(s.shade??62)/100})`;$("backdrop").style.filter=`blur(${s.blur??8}px)`;$("backdrop").style.backgroundImage=s.bg?`url("${s.bg}")`:"linear-gradient(135deg,#162b50,#07111e)"}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");refresh();