const DB="corte_paquetes_v1_9",$=id=>document.getElementById(id);
const dk=d=>{d=new Date(d);return isNaN(d)?null:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const pd=s=>{if(!s)return new Date(NaN);let[a,b,c]=s.split("-").map(Number);return new Date(a,b-1,c)};
function wk(d){d=new Date(d);d.setHours(0,0,0,0);d.setDate(d.getDate()+3-(d.getDay()+6)%7);let y=d.getFullYear(),f=new Date(y,0,4);return y+"-"+(1+Math.round(((d-f)/864e5-f.getDay()+1)/7))}
function bounds(){let n=new Date(),m=new Date(n),x=(n.getDay()+6)%7;m.setDate(n.getDate()-x);m.setHours(0,0,0,0);let s=new Date(m);s.setDate(m.getDate()+6);s.setHours(23,59,59,999);return[m,s]}
const empty=()=>({data:{},rates:{},advances:{},settings:{shade:62,blur:8,bg:null}});
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||"null")}catch{return null}};
function migrate(){let db=read(DB)||empty();db.data??={};db.rates??={};db.advances??={};db.settings??={shade:62,blur:8,bg:null};for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i),x=read(k);if(!x||k===DB||typeof x!=="object")continue;if(x.data)Object.entries(x.data).forEach(([key,v])=>{let m=String(key).match(/(20\d{2})[-_\/](\d{1,2})[-_\/](\d{1,2})/);if(m){let d=`${m[1]}-${String(m[2]).padStart(2,"0")}-${String(m[3]).padStart(2,"0")}`;db.data[wk(pd(d))+"_"+d]=Number(v)||0}});if(x.rates)Object.assign(x.rates,x.rates);if(x.settings)db.settings={...x.settings,...db.settings};if(x.advances)db.advances={...x.advances,...db.advances}}localStorage.setItem(DB,JSON.stringify(db));return db}
const load=()=>migrate(),save=x=>localStorage.setItem(DB,JSON.stringify(x));
const money=n=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(Number(n)||0);
function rate(db,d){let a=Object.keys(db.rates).filter(x=>x<=d).sort();return a.length?Number(db.rates[a.at(-1)])||0:0}
function renderStats(es,db){let vals=es.map(x=>x.v),sum=vals.reduce((a,b)=>a+b,0),avg=es.length?sum/es.length:0,best=vals.length?Math.max(...vals):0,bestEntry=es.find(x=>x.v===best),avgMoney=es.length?es.reduce((a,x)=>a+x.v*rate(db,x.date),0)/es.length:0;$("avg").textContent=avg.toFixed(1);$("best").textContent=bestEntry?best+"":0;$("worked").textContent=es.length+"/7";$("pace").textContent=money(avgMoney);let names=["L","M","X","J","V","S","D"],map={};es.forEach(x=>map[pd(x.date).getDay()]=x.v);let max=Math.max(1,...Object.values(map));$("chart").innerHTML=names.map((n,i)=>{let js=(i+1)%7,v=map[js]||0,h=v?Math.max(8,Math.round(v/max*82)):4;return `<div class="bar" style="height:${h}px;opacity:${v?1:.22}"><span>${n}</span></div>`}).join("")}
function refresh(){let db=load(),w=wk(new Date()),es=Object.entries(db.data).filter(([k])=>k.startsWith(w+"_")).map(([k,v])=>({date:k.slice(3),v:Number(v)||0})).sort((a,b)=>a.date.localeCompare(b.date)),r=rate(db,dk(new Date())),total=es.reduce((a,x)=>a+x.v,0),ad=db.advances[w]||[],at=ad.reduce((a,x)=>a+Number(x.amount||0),0),[m,s]=bounds();$("week").textContent="Semana "+w.split("-")[1];$("range").textContent=`Lunes ${m.getDate()} – Domingo ${s.getDate()} de ${s.toLocaleDateString("es-MX",{month:"long",year:"numeric"})}`;$("footerRange").textContent=`${m.getDate()} – ${s.getDate()} de ${s.toLocaleDateString("es-MX",{month:"long",year:"numeric"})}`;$("total").textContent=total;$("daysText").textContent=es.length?es.length+" días registrados":"Sin registros";$("gross").textContent=money(total*r);$("rateText").textContent=money(r);$("adv").textContent="-"+money(at);$("advCount").textContent=ad.length;$("net").textContent=money(total*r-at);$("count").textContent=es.length+" días";$("curRate").textContent=money(r);$("rate").value=r||"";$("date").min=dk(m);$("date").max=dk(s);if(!$("date").value||$("date").value<dk(m)||$("date").value>dk(s))$("date").value=dk(new Date());$("advDate").min=dk(m);$("advDate").max=dk(s);if(!$("advDate").value)$("advDate").value=dk(new Date());$("dateText").textContent="Seleccionado: "+pd($("date").value).toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("list").innerHTML=es.length?es.map(e=>{let d=pd(e.date),rr=rate(db,e.date);return `<div class="row"><div class="dateLabel">${d.toLocaleDateString("es-MX",{day:"numeric",month:"long",year:"numeric"})}<small>${d.toLocaleDateString("es-MX",{weekday:"long"})}</small></div><div class="rowRight"><b>${e.v} paquetes</b><small>${money(e.v*rr)}</small></div><div><button class="mini" onclick="editDay('${e.date}')">✏️</button><button class="mini" onclick="delDay('${e.date}')">🗑️</button></div></div>`}).join(""):"Aún no hay registros.";renderStats(es,db);renderHistory(db,w);renderAdvances(ad);apply(db.settings)}
function renderHistory(db,w){let ws=[...new Set(Object.keys(db.data).map(k=>k.split("_")[0]))].sort().reverse();$("history").innerHTML=ws.length?ws.map(x=>{let en=Object.entries(db.data).filter(([k])=>k.startsWith(x+"_")),t=en.reduce((a,[,v])=>a+Number(v||0),0),last=en.map(([k])=>k.slice(3)).sort().at(-1),rr=last?rate(db,last):0,a=(db.advances[x]||[]).reduce((z,q)=>z+Number(q.amount||0),0);return `<div class="row"><div class="dateLabel">Semana ${x.split("-")[1]}<small>${money(rr)} / paquete · adelantos ${money(a)}</small></div><div class="rowRight"><b>${t} paquetes</b><small>${money(t*rr-a)} a recibir</small></div></div>`}).join(""):"Todavía no hay semanas anteriores."}
function renderAdvances(a){$("advList").innerHTML=a.length?a.map((x,i)=>`<div class="row"><div class="dateLabel">${esc(x.concept||"Préstamo")}<small>${pd(x.date).toLocaleDateString("es-MX",{day:"numeric",month:"long"})}</small></div><div class="rowRight"><b>-${money(x.amount)}</b></div><button class="mini" onclick="delAdv(${i})">🗑️</button></div>`).join(""):"No hay adelantos."}
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
$("save").onclick=()=>{let n=Number($("qty").value),date=$("date").value,[m,s]=bounds(),d=pd(date);if(!Number.isFinite(n)||n<0||d<m||d>s){alert("Selecciona un día de la semana actual.");return}let db=load();db.data[wk(d)+"_"+date]=Math.floor(n);save(db);$("qty").value="";refresh()};
$("date").onchange=()=>{$("dateText").textContent="Seleccionado: "+pd($("date").value).toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"})};
$("saveRate").onclick=()=>{let n=Number($("rate").value);if(!Number.isFinite(n)||n<0)return;let db=load();db.rates[dk(new Date())]=n;save(db);refresh()};
$("addAdv").onclick=$("addAdv2").onclick=()=>{$("advDate").value=dk(new Date());$("advPanel").classList.remove("hidden")};
$("cancelAdv").onclick=()=>$("advPanel").classList.add("hidden");
$("saveAdv").onclick=()=>{let a=Number($("amount").value),c=$("concept").value.trim()||"Préstamo",date=$("advDate").value,[m,s]=bounds(),d=pd(date);if(!Number.isFinite(a)||a<=0||d<m||d>s){alert("Selecciona un día de la semana actual.");return}let db=load(),w=wk(d);db.advances[w]??=[];db.advances[w].push({amount:a,concept:c,date});save(db);$("advPanel").classList.add("hidden");$("amount").value="";$("concept").value="";refresh()};
window.delAdv=i=>{let db=load(),w=wk(new Date);if(confirm("¿Eliminar adelanto?")){db.advances[w].splice(i,1);save(db);refresh()}};
window.editDay=s=>{$("editPanel").dataset.date=s;$("editQty").value=load().data[wk(pd(s))+"_"+s]||0;$("editPanel").classList.remove("hidden")};$("cancelEdit").onclick=()=>$("editPanel").classList.add("hidden");$("saveEdit").onclick=()=>{let s=$("editPanel").dataset.date,n=Number($("editQty").value);if(n<0||!Number.isFinite(n))return;let db=load();db.data[wk(pd(s))+"_"+s]=Math.floor(n);save(db);$("editPanel").classList.add("hidden");refresh()};window.delDay=s=>{if(confirm("¿Eliminar registro?")){let db=load();delete db.data[wk(pd(s))+"_"+s];save(db);refresh()}};
$("reset").onclick=()=>{if(confirm("¿Borrar registros y adelantos de esta semana?")){let db=load(),w=wk(new Date);Object.keys(db.data).filter(k=>k.startsWith(w+"_")).forEach(k=>delete db.data[k]);delete db.advances[w];save(db);refresh()}};
$("historyToggle").onclick=()=>{let x=$("historyWrap");x.classList.toggle("open");$("historyToggle").textContent=x.classList.contains("open")?"⌃":"⌄"};
$("settingsBtn").onclick=()=>$("setPanel").classList.remove("hidden");$("closeSet").onclick=()=>$("setPanel").classList.add("hidden");
$("bg").onchange=e=>{let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{let db=load();db.settings.bg=r.result;save(db);apply(db.settings)};r.readAsDataURL(f)};$("removeBg").onclick=()=>{let db=load();db.settings.bg=null;save(db);apply(db.settings)};$("shadeRange").oninput=e=>{let db=load();db.settings.shade=Number(e.target.value);save(db);apply(db.settings)};$("blurRange").oninput=e=>{let db=load();db.settings.blur=Number(e.target.value);save(db);apply(db.settings)};
function apply(s={}){$("shadeRange").value=s.shade??62;$("blurRange").value=s.blur??8;$("shadeOut").textContent=(s.shade??62)+"%";$("blurOut").textContent=(s.blur??8)+"px";$("shade").style.background=`rgba(2,5,16,${(s.shade??62)/100})`;$("backdrop").style.filter=`blur(${s.blur??8}px)`;$("backdrop").style.backgroundImage=s.bg?`url("${s.bg}")`:"radial-gradient(circle at 20% 10%,#17285c,#050814 55%,#12051f)"}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").then(r=>r.update()).catch(()=>{});refresh();